const messages = {
  validation: 'Enter a valid input. Spaces are not allowed.',
  createSuccess: 'Device created successfully.',
  fieldCheck: 'Please fill in all required fields.',
  createError: 'Creation failed. Unable to process the request.',
  createMessage: "You haven't added any devices yet. Click 'Create' to add one.",
  readError: 'Failed to retrieve device information.',
  updateSuccess: 'Device updated successfully.',
  updateError: 'No changes detected. Data remains unchanged.',
  deleteSuccess: 'Device deleted successfully.',
  deleteError: 'Failed to delete device. Please try again later.',
  feedEmpty: 'Your feed is empty.',
  serverError: 'Something went wrong. Please try again later.',
  signUpSuccess: 'Signup successful.',
  signInSuccess: 'Login successful.',
  tokenNotVerified: 'Token not verified.',
  usernameExists: 'Username already exists.',
  emailExists: 'Email already exists.',
  userNotFound: "User doesn't exist.",
  invalidPassword: 'Invalid password.',
  auth: {
    inValidToken: 'Invalid token.',
    tokenMissing: 'Authorization token is missing or invalid.',
    missing: 'Username or password is missing.',
    hashingError: 'Error while hashing the password.',
    missingPassword: 'Password is required.',
  },
  requestSentToAccessDevice: 'Request to access device sent successfully.',
  requestToAccessDeviceError: 'Request to access device failed.',
  approvedRequestError: 'No approved request found',
  removeDeniedRequestError: 'Request can not remove',
  deniedRequestError: 'No approved request found',
  pendingRequestsError: 'No pending requests found.',
  allowedAccess: 'Access granted for the device.',
  allowedAccessError: 'Failed to grant access for the device.',
  deniedAccess: 'Access to the device has been successfully denied.',
  deniedAccessError: 'Failed to deny access to the device.',
};

export default messages;
